### ISSUE TITLE
Preview failed on OS X

### ISSUE THREAD

**Issue by lextm** [tht13/RST-vscode#2]
Initially the error was,
```
'/Applications/Visual Studio Code.app/Contents/MacOS/Electron' --debugBrkPluginHost=49549 --extensionDevelopmentPath=/Users/lextm/RST-vscode 
Loading development extension at /Users/lextm/RST-vscode
Error
Command failed: /bin/sh -c python /Users/lextm/RST-vscode/src/preview.py /Users/lextm/linpeiman/articles/a_story_you_should_have_known.rst
Traceback (most recent call last):
  File "/Users/lextm/RST-vscode/src/preview.py", line 2, in <module>
    from docutils import core
ImportError: No module named docutils
Error: Command failed: /bin/sh -c python /Users/lextm/RST-vscode/src/preview.py /Users/lextm/linpeiman/articles/a_story_you_should_have_known.rst
Traceback (most recent call last):
  File "/Users/lextm/RST-vscode/src/preview.py", line 2, in <module>
    from docutils import core
ImportError: No module named docutils
    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

The fix is to run `pip install docutils`. 

You might update the documentation to say this extension depends on both Python and DocUtils.

By the way, I will merge the preview feature into [another reStructuredText extension I maintained](https://github.com/lextm/vscode-restructuredtext), which is also under MIT license.

**Comment by lextm** [comment]
My extension has been updated with `sphinx-build` enabled live preview,

https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext

Close this issue now.
