### ISSUE TITLE
build-in docutils can't work under python3

### ISSUE THREAD

**Issue by ywyt738** [tht13/RST-vscode#8]
I'm using cmder in windows, so don't care **λ**.
```
C:\Users\admin\.vscode\extensions\tht13.rst-vscode-2.0.0\src\python
λ python preview.py g:\my_note\source\installation_openssh.rst
Traceback (most recent call last):
  File "preview.py", line 6, in <module>
    from docutils import core
  File "C:\Users\huangxiaojun\.vscode\extensions\tht13.rst-vscode-2.0.0\src\python\docutils\__init__.py", line 68, in <module>
    class ApplicationError(StandardError):
NameError: name 'StandardError' is not defined
```
I replace the docutils package with package which installed from pypi and it works.

**Comment by tht13** [comment]
Fixed in version 3.0.0
